#!/usr/bin/make
# Automatically generated by KiBot from `spora.kibot.yaml`
KIBOT=kibot
DEBUG=
CONFIG=spora.kibot.yaml
SCH=spora.sch
PCB=spora.kicad_pcb
DEST=Fabrication
KIBOT_CMD=$(KIBOT) $(DEBUG) -c $(CONFIG) -e $(SCH) -b $(PCB) -d $(DEST)
LOGFILE=kibot_error.log

#
# Default target
#
all: run_erc run_drc Elecrow_gerbers Elecrow_drill Elecrow FusionPCB_gerbers FusionPCB_drill FusionPCB JLCPCB_gerbers JLCPCB_drill JLCPCB P-Ban_gerbers P-Ban_drill P-Ban PCBWay_gerbers PCBWay_drill PCBWay print_sch print_front print_bottom print_gnd print_power print_s1 print_s2 interactive_bom bom_html bom_xlsx bom_csv gerbers excellon_drill gerber_drills position pcb_top_g pcb_bot_g pcb_top_b pcb_bot_b pcb_top_r pcb_bot_r step

#
# SCH/PCB targets
#
pre_sch: run_erc

out_sch: print_sch bom_html bom_xlsx bom_csv

all_sch: pre_sch out_sch

pre_pcb: run_drc

out_pcb: Elecrow_gerbers Elecrow_drill Elecrow FusionPCB_gerbers FusionPCB_drill FusionPCB JLCPCB_gerbers JLCPCB_drill JLCPCB P-Ban_gerbers P-Ban_drill P-Ban PCBWay_gerbers PCBWay_drill PCBWay print_front print_bottom print_gnd print_power print_s1 print_s2 interactive_bom gerbers excellon_drill gerber_drills position pcb_top_g pcb_bot_g pcb_top_b pcb_bot_b pcb_top_r pcb_bot_r step

all_pcb: pre_pcb out_pcb

#
# Available targets (outputs)
#
run_erc: Fabrication/spora-erc_0.1.txt

run_drc: Fabrication/spora-drc_0.1.txt

Elecrow_gerbers: Fabrication/Elecrow/spora.GTL Fabrication/Elecrow/spora.G1 Fabrication/Elecrow/spora.G2 Fabrication/Elecrow/spora.G3 Fabrication/Elecrow/spora.G4 Fabrication/Elecrow/spora.GBL Fabrication/Elecrow/spora.GTO Fabrication/Elecrow/spora.GBO Fabrication/Elecrow/spora.GTS Fabrication/Elecrow/spora.GBS Fabrication/Elecrow/spora.GML

Elecrow_drill: Fabrication/Elecrow/spora.TXT Fabrication/Elecrow/spora-NPTH.TXT

Elecrow: Fabrication/Elecrow/spora-Elecrow_0.1.zip

FusionPCB_gerbers: Fabrication/FusionPCB/spora.GTL Fabrication/FusionPCB/spora.GL2 Fabrication/FusionPCB/spora.GL3 Fabrication/FusionPCB/spora.GL4 Fabrication/FusionPCB/spora.GL5 Fabrication/FusionPCB/spora.GBL Fabrication/FusionPCB/spora.GTO Fabrication/FusionPCB/spora.GBO Fabrication/FusionPCB/spora.GTS Fabrication/FusionPCB/spora.GBS Fabrication/FusionPCB/spora.GML

FusionPCB_drill: Fabrication/FusionPCB/spora.TXT

FusionPCB: Fabrication/FusionPCB/spora-FusionPCB_0.1.zip

JLCPCB_gerbers: Fabrication/JLCPCB/spora-F_Cu_0.1.gbr Fabrication/JLCPCB/spora-B_Cu_0.1.gbr Fabrication/JLCPCB/spora-In1_Cu_0.1.gbr Fabrication/JLCPCB/spora-In2_Cu_0.1.gbr Fabrication/JLCPCB/spora-In3_Cu_0.1.gbr Fabrication/JLCPCB/spora-In4_Cu_0.1.gbr Fabrication/JLCPCB/spora-F_SilkS_0.1.gbr Fabrication/JLCPCB/spora-B_SilkS_0.1.gbr Fabrication/JLCPCB/spora-F_Mask_0.1.gbr Fabrication/JLCPCB/spora-B_Mask_0.1.gbr Fabrication/JLCPCB/spora-Edge_Cuts_0.1.gbr

JLCPCB_drill: Fabrication/JLCPCB/spora-PTH.drl Fabrication/JLCPCB/spora-NPTH.drl

JLCPCB: Fabrication/JLCPCB/spora-JLCPCB_0.1.zip

P-Ban_gerbers: Fabrication/P-Ban/spora-F_Cu_0.1.gtl Fabrication/P-Ban/spora-B_Cu_0.1.gbl Fabrication/P-Ban/spora-In1_Cu_0.1.gp1 Fabrication/P-Ban/spora-In2_Cu_0.1.gp2 Fabrication/P-Ban/spora-In3_Cu_0.1.gp3 Fabrication/P-Ban/spora-In4_Cu_0.1.gp4 Fabrication/P-Ban/spora-F_SilkS_0.1.gto Fabrication/P-Ban/spora-B_SilkS_0.1.gbo Fabrication/P-Ban/spora-F_Mask_0.1.gts Fabrication/P-Ban/spora-B_Mask_0.1.gbs Fabrication/P-Ban/spora-Edge_Cuts_0.1.gm1 Fabrication/P-Ban/製造基準書.txt

P-Ban_drill: Fabrication/P-Ban/spora.drl Fabrication/P-Ban/spora-drill_map_0.1.gbr Fabrication/P-Ban/spora-drl.rpt

P-Ban: Fabrication/P-Ban/spora-P-Ban_0.1.zip

PCBWay_gerbers: Fabrication/PCBWay/spora.gtl Fabrication/PCBWay/spora.gl2 Fabrication/PCBWay/spora.gl3 Fabrication/PCBWay/spora.gl4 Fabrication/PCBWay/spora.gl5 Fabrication/PCBWay/spora.gbl Fabrication/PCBWay/spora.gto Fabrication/PCBWay/spora.gbo Fabrication/PCBWay/spora.gts Fabrication/PCBWay/spora.gbs Fabrication/PCBWay/spora.gtp Fabrication/PCBWay/spora.gbp Fabrication/PCBWay/spora.gm1

PCBWay_drill: Fabrication/PCBWay/spora.drl Fabrication/PCBWay/spora-NPTH.drl

PCBWay: Fabrication/PCBWay/spora-PCBWay_0.1.zip

print_sch: Fabrication/spora-schematic_0.1.pdf

print_front: Fabrication/spora-F_Cu+Dwgs_User_0.1.pdf

print_bottom: Fabrication/spora-B_Cu+Dwgs_User_0.1.pdf

print_gnd: Fabrication/spora-GND+Dwgs_User_0.1.pdf

print_power: Fabrication/spora-Power_+3,3V+Dwgs_User_0.1.pdf

print_s1: Fabrication/spora-S1_Cu+Dwgs_User_0.1.pdf

print_s2: Fabrication/spora-S2_Cu+Dwgs_User_0.1.pdf

interactive_bom: Fabrication/BoM/spora-ibom_0.1.html

bom_html: Fabrication/BoM/spora-bom_0.1.html

bom_xlsx: Fabrication/BoM/spora-bom_0.1.xlsx

bom_csv: Fabrication/BoM/spora-bom_0.1.csv

gerbers: Fabrication/Gerbers/spora-F_Cu_0.1.gbr Fabrication/Gerbers/spora-B_Cu_0.1.gbr Fabrication/Gerbers/spora-GND_Cu_0.1.gbr Fabrication/Gerbers/spora-Power_Cu_0.1.gbr Fabrication/Gerbers/spora-S1_Cu_0.1.gbr Fabrication/Gerbers/spora-S2_Cu_0.1.gbr Fabrication/Gerbers/spora-F_Paste_0.1.gbr Fabrication/Gerbers/spora-B_Paste_0.1.gbr Fabrication/Gerbers/spora-F_SilkS_0.1.gbr Fabrication/Gerbers/spora-B_SilkS_0.1.gbr Fabrication/Gerbers/spora-F_Mask_0.1.gbr Fabrication/Gerbers/spora-B_Mask_0.1.gbr Fabrication/Gerbers/spora-Dwgs_User_0.1.gbr Fabrication/Gerbers/spora-Edge_Cuts_0.1.gbr Fabrication/Gerbers/spora-B_Fab_0.1.gbr Fabrication/Gerbers/spora-job.gbrjob

excellon_drill: Fabrication/Drill/spora-PTH_drill_0.1.drl Fabrication/Drill/spora-PTH_drill_map_0.1.pdf Fabrication/Drill/spora-NPTH_drill_0.1.drl Fabrication/Drill/spora-NPTH_drill_map_0.1.pdf Fabrication/Drill/spora-drl.rpt

gerber_drills: Fabrication/Drill/spora-PTH_drill_0.1.gbr Fabrication/Drill/spora-NPTH_drill_0.1.gbr

position: Fabrication/Position/spora-top_pos_0.1.pos Fabrication/Position/spora-bottom_pos_0.1.pos

pcb_top_g: Fabrication/PCB/green/spora-top_0.1.jpg

pcb_bot_g: Fabrication/PCB/green/spora-bottom_0.1.jpg

pcb_top_b: Fabrication/PCB/blue/spora-top_0.1.jpg

pcb_bot_b: Fabrication/PCB/blue/spora-bottom_0.1.jpg

pcb_top_r: Fabrication/PCB/red/spora-top_0.1.jpg

pcb_bot_r: Fabrication/PCB/red/spora-bottom_0.1.jpg

step: Fabrication/3D/spora-3D_0.1.step

#
# Rules and dependencies
#
Fabrication/spora-erc_0.1.txt: Power.sch spora.sch spora.kibot.yaml
	@$(KIBOT_CMD) -s run_drc -i 2>> $(LOGFILE)

Fabrication/spora-drc_0.1.txt: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s run_erc -i 2>> $(LOGFILE)

# Gerbers compatible with Elecrow
Fabrication/Elecrow/spora.GTL Fabrication/Elecrow/spora.G1 Fabrication/Elecrow/spora.G2 Fabrication/Elecrow/spora.G3 Fabrication/Elecrow/spora.G4 Fabrication/Elecrow/spora.GBL Fabrication/Elecrow/spora.GTO Fabrication/Elecrow/spora.GBO Fabrication/Elecrow/spora.GTS Fabrication/Elecrow/spora.GBS Fabrication/Elecrow/spora.GML: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all Elecrow_gerbers 2>> $(LOGFILE)

# Drill files compatible with Elecrow
Fabrication/Elecrow/spora.TXT Fabrication/Elecrow/spora-NPTH.TXT: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all Elecrow_drill 2>> $(LOGFILE)

# ZIP file for Elecrow
Fabrication/Elecrow/spora-Elecrow_0.1.zip: spora.kibot.yaml
	@$(KIBOT_CMD) -s all Elecrow 2>> $(LOGFILE)

# Gerbers compatible with FusionPCB
Fabrication/FusionPCB/spora.GTL Fabrication/FusionPCB/spora.GL2 Fabrication/FusionPCB/spora.GL3 Fabrication/FusionPCB/spora.GL4 Fabrication/FusionPCB/spora.GL5 Fabrication/FusionPCB/spora.GBL Fabrication/FusionPCB/spora.GTO Fabrication/FusionPCB/spora.GBO Fabrication/FusionPCB/spora.GTS Fabrication/FusionPCB/spora.GBS Fabrication/FusionPCB/spora.GML: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all FusionPCB_gerbers 2>> $(LOGFILE)

# Drill files compatible with FusionPCB
Fabrication/FusionPCB/spora.TXT: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all FusionPCB_drill 2>> $(LOGFILE)

# ZIP file for FusionPCB
Fabrication/FusionPCB/spora-FusionPCB_0.1.zip: spora.kibot.yaml
	@$(KIBOT_CMD) -s all FusionPCB 2>> $(LOGFILE)

# Gerbers compatible with JLCPCB
Fabrication/JLCPCB/spora-F_Cu_0.1.gbr Fabrication/JLCPCB/spora-B_Cu_0.1.gbr Fabrication/JLCPCB/spora-In1_Cu_0.1.gbr Fabrication/JLCPCB/spora-In2_Cu_0.1.gbr Fabrication/JLCPCB/spora-In3_Cu_0.1.gbr Fabrication/JLCPCB/spora-In4_Cu_0.1.gbr Fabrication/JLCPCB/spora-F_SilkS_0.1.gbr Fabrication/JLCPCB/spora-B_SilkS_0.1.gbr Fabrication/JLCPCB/spora-F_Mask_0.1.gbr Fabrication/JLCPCB/spora-B_Mask_0.1.gbr Fabrication/JLCPCB/spora-Edge_Cuts_0.1.gbr: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all JLCPCB_gerbers 2>> $(LOGFILE)

# Drill files compatible with JLCPCB
Fabrication/JLCPCB/spora-PTH.drl Fabrication/JLCPCB/spora-NPTH.drl: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all JLCPCB_drill 2>> $(LOGFILE)

# ZIP file for JLCPCB
Fabrication/JLCPCB/spora-JLCPCB_0.1.zip: spora.kibot.yaml
	@$(KIBOT_CMD) -s all JLCPCB 2>> $(LOGFILE)

# Gerbers compatible with P-Ban
Fabrication/P-Ban/spora-F_Cu_0.1.gtl Fabrication/P-Ban/spora-B_Cu_0.1.gbl Fabrication/P-Ban/spora-In1_Cu_0.1.gp1 Fabrication/P-Ban/spora-In2_Cu_0.1.gp2 Fabrication/P-Ban/spora-In3_Cu_0.1.gp3 Fabrication/P-Ban/spora-In4_Cu_0.1.gp4 Fabrication/P-Ban/spora-F_SilkS_0.1.gto Fabrication/P-Ban/spora-B_SilkS_0.1.gbo Fabrication/P-Ban/spora-F_Mask_0.1.gts Fabrication/P-Ban/spora-B_Mask_0.1.gbs Fabrication/P-Ban/spora-Edge_Cuts_0.1.gm1 Fabrication/P-Ban/製造基準書.txt: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all P-Ban_gerbers 2>> $(LOGFILE)

# Drill files compatible with P-Ban
Fabrication/P-Ban/spora.drl Fabrication/P-Ban/spora-drill_map_0.1.gbr Fabrication/P-Ban/spora-drl.rpt: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all P-Ban_drill 2>> $(LOGFILE)

# ZIP file for P-Ban
Fabrication/P-Ban/spora-P-Ban_0.1.zip: spora.kibot.yaml
	@$(KIBOT_CMD) -s all P-Ban 2>> $(LOGFILE)

# Gerbers compatible with PCBWay
Fabrication/PCBWay/spora.gtl Fabrication/PCBWay/spora.gl2 Fabrication/PCBWay/spora.gl3 Fabrication/PCBWay/spora.gl4 Fabrication/PCBWay/spora.gl5 Fabrication/PCBWay/spora.gbl Fabrication/PCBWay/spora.gto Fabrication/PCBWay/spora.gbo Fabrication/PCBWay/spora.gts Fabrication/PCBWay/spora.gbs Fabrication/PCBWay/spora.gtp Fabrication/PCBWay/spora.gbp Fabrication/PCBWay/spora.gm1: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all PCBWay_gerbers 2>> $(LOGFILE)

# Drill files compatible with PCBWay
Fabrication/PCBWay/spora.drl Fabrication/PCBWay/spora-NPTH.drl: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all PCBWay_drill 2>> $(LOGFILE)

# ZIP file for PCBWay
Fabrication/PCBWay/spora-PCBWay_0.1.zip: spora.kibot.yaml
	@$(KIBOT_CMD) -s all PCBWay 2>> $(LOGFILE)

# Print schematic (PDF)
Fabrication/spora-schematic_0.1.pdf: Power.sch spora.sch spora.kibot.yaml
	@$(KIBOT_CMD) -s all print_sch 2>> $(LOGFILE)

# Print F.Cu+Dwgs.User
Fabrication/spora-F_Cu+Dwgs_User_0.1.pdf: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all print_front 2>> $(LOGFILE)

# Print B.Cu+Dwgs.User
Fabrication/spora-B_Cu+Dwgs_User_0.1.pdf: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all print_bottom 2>> $(LOGFILE)

# Print GND+Dwgs.User
Fabrication/spora-GND+Dwgs_User_0.1.pdf: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all print_gnd 2>> $(LOGFILE)

# Print Power_+3,3V+Dwgs.User
Fabrication/spora-Power_+3,3V+Dwgs_User_0.1.pdf: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all print_power 2>> $(LOGFILE)

# Print Señal_1+Dwgs.User
Fabrication/spora-S1_Cu+Dwgs_User_0.1.pdf: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all print_s1 2>> $(LOGFILE)

# Print Señal_2+Dwgs.User
Fabrication/spora-S2_Cu+Dwgs_User_0.1.pdf: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all print_s2 2>> $(LOGFILE)

# Interactive Bill of Materials (HTML)
Fabrication/BoM/spora-ibom_0.1.html: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all interactive_bom 2>> $(LOGFILE)

# Bill of Materials in HTML format
Fabrication/BoM/spora-bom_0.1.html: Power.sch spora.sch spora.kibot.yaml
	@$(KIBOT_CMD) -s all bom_html 2>> $(LOGFILE)

# Bill of Materials in XLSX format
Fabrication/BoM/spora-bom_0.1.xlsx: Power.sch spora.sch spora.kibot.yaml
	@$(KIBOT_CMD) -s all bom_xlsx 2>> $(LOGFILE)

# Bill of Materials in CSV format
Fabrication/BoM/spora-bom_0.1.csv: Power.sch spora.sch spora.kibot.yaml
	@$(KIBOT_CMD) -s all bom_csv 2>> $(LOGFILE)

# Gerbers for the board house
Fabrication/Gerbers/spora-F_Cu_0.1.gbr Fabrication/Gerbers/spora-B_Cu_0.1.gbr Fabrication/Gerbers/spora-GND_Cu_0.1.gbr Fabrication/Gerbers/spora-Power_Cu_0.1.gbr Fabrication/Gerbers/spora-S1_Cu_0.1.gbr Fabrication/Gerbers/spora-S2_Cu_0.1.gbr Fabrication/Gerbers/spora-F_Paste_0.1.gbr Fabrication/Gerbers/spora-B_Paste_0.1.gbr Fabrication/Gerbers/spora-F_SilkS_0.1.gbr Fabrication/Gerbers/spora-B_SilkS_0.1.gbr Fabrication/Gerbers/spora-F_Mask_0.1.gbr Fabrication/Gerbers/spora-B_Mask_0.1.gbr Fabrication/Gerbers/spora-Dwgs_User_0.1.gbr Fabrication/Gerbers/spora-Edge_Cuts_0.1.gbr Fabrication/Gerbers/spora-B_Fab_0.1.gbr Fabrication/Gerbers/spora-job.gbrjob: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all gerbers 2>> $(LOGFILE)

# Excellon drill files
Fabrication/Drill/spora-PTH_drill_0.1.drl Fabrication/Drill/spora-PTH_drill_map_0.1.pdf Fabrication/Drill/spora-NPTH_drill_0.1.drl Fabrication/Drill/spora-NPTH_drill_map_0.1.pdf Fabrication/Drill/spora-drl.rpt: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all excellon_drill 2>> $(LOGFILE)

# Gerber drill files
Fabrication/Drill/spora-PTH_drill_0.1.gbr Fabrication/Drill/spora-NPTH_drill_0.1.gbr: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all gerber_drills 2>> $(LOGFILE)

# Pick and place file
Fabrication/Position/spora-top_pos_0.1.pos Fabrication/Position/spora-bottom_pos_0.1.pos: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all position 2>> $(LOGFILE)

# PCB render top green
Fabrication/PCB/green/spora-top_0.1.jpg: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all pcb_top_g 2>> $(LOGFILE)

# PCB render bottom green
Fabrication/PCB/green/spora-bottom_0.1.jpg: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all pcb_bot_g 2>> $(LOGFILE)

# PCB render top blue
Fabrication/PCB/blue/spora-top_0.1.jpg: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all pcb_top_b 2>> $(LOGFILE)

# PCB render bottom blue
Fabrication/PCB/blue/spora-bottom_0.1.jpg: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all pcb_bot_b 2>> $(LOGFILE)

# PCB render top red
Fabrication/PCB/red/spora-top_0.1.jpg: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all pcb_top_r 2>> $(LOGFILE)

# PCB render bottom red
Fabrication/PCB/red/spora-bottom_0.1.jpg: spora.kicad_pcb spora.kibot.yaml
	@$(KIBOT_CMD) -s all pcb_bot_r 2>> $(LOGFILE)

# Generate 3D model (STEP)
Fabrication/3D/spora-3D_0.1.step: spora.kicad_pcb ../modelos.3dshapes/B3U_3000PB.wrl ../modelos.3dshapes/MPU-9250.wrl ../modelos.3dshapes/usb_B_micro_smd.wrl ../modelos.3dshapes/MCP73821.wrl ../modelos.3dshapes/c_0201.wrl ../modelos.3dshapes/c_0402.wrl ../modelos.3dshapes/LBCA2HNZYZ-711.wrl ../modelos.3dshapes/MKL03Z32CAF4R_20-WLCSP_1.995x1.609.wrl ../modelos.3dshapes/sod323.wrl ../modelos.3dshapes/TPS2115A.wrl ../modelos.3dshapes/ABS05-32.768KHZ-9-T.wrl ../modelos.3dshapes/r_0402.wrl ../modelos.3dshapes/SML-LX0404SIUPGUSB.wrl ../modelos.3dshapes/df12(3.0)-10dp-0.5v.wrl ../modelos.3dshapes/r_0201.wrl ../modelos.3dshapes/TPS82740B.wrl spora.kibot.yaml
	@$(KIBOT_CMD) -s all step 2>> $(LOGFILE)

.PHONY: all pre_sch out_sch all_sch pre_pcb out_pcb all_pcb run_erc run_drc Elecrow_gerbers Elecrow_drill Elecrow FusionPCB_gerbers FusionPCB_drill FusionPCB JLCPCB_gerbers JLCPCB_drill JLCPCB P-Ban_gerbers P-Ban_drill P-Ban PCBWay_gerbers PCBWay_drill PCBWay print_sch print_front print_bottom print_gnd print_power print_s1 print_s2 interactive_bom bom_html bom_xlsx bom_csv gerbers excellon_drill gerber_drills position pcb_top_g pcb_bot_g pcb_top_b pcb_bot_b pcb_top_r pcb_bot_r step
